### ISSUE TITLE
Is a pre-trained model available for usage?

### ISSUE THREAD

**Issue by Gigarrum** [qgao21/CoreDiff#14]
Hello!

I would like to know if the pre-trained model is available somewhere? I haven't found it in this repository...

**Comment by qgao21** [comment]
I have uploaded the pre-trained model on the original Mayo 2016 'DICOM' format data (25% dose): https://drive.google.com/drive/folders/1rGb34H_6ktP79vMYYJOLSoCE3579TDZ5?usp=drive_link.

**Comment by kklay11** [comment]
![image](https://github.com/user-attachments/assets/86d47b5f-c861-4e62-9652-50edd824dccf)
作者你好，我看到您只上传了ema_model一个文件。test报错发现还需要其他两个模型文件

**Comment by kklay11** [comment]
> ![image](https://private-user-images.githubusercontent.com/103831184/378653613-86d47b5f-c861-4e62-9652-50edd824dccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjU0NjMsIm5iZiI6MTcyOTU2NTE2MywicGF0aCI6Ii8xMDM4MzExODQvMzc4NjUzNjEzLTg2ZDQ3YjVmLWM4NjEtNGU2Mi05NjUyLTUwZWRkODI0ZGNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMjQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmMyYjJhMTJkNjNiZTliOGViNWYxYjc3NjA5NThmOTU1ZTljZDUxYjZjYTRmZDc0YTU0NGRlNGJhMDI5MDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.en_g58xJBMeJceWytdG4yGxu55JF-sexpJ6uJfH8jzU) 作者你好，我看到您只上传了ema_model一个文件。test报错发现还需要其他两个模型文件
> 
> 还有一个问题，我复现了两次mayo_2016的结果各指标都比您论文中的低不少（比如psnr我是41左右，您原文43.92±1.33），代码计算指标啥的都没动，期待您的解答 @qgao21

<img width="723" alt="PixPin_2024-10-22_10-40-39" src="https://github.com/user-attachments/assets/d7e28b89-29c9-46b5-8d4b-4f88ea6a4bc8">
我修改了代码，用了您上传的ema模型文件test的结果数值也是这样的

**Comment by qgao21** [comment]
您好，
- ema_model是用于推理的模型，model和optimizer不需要加载。我已更新了models/basic_template.py和utils/loggerx.py，并上传了test_mayo2016.sh供推理使用。
- 基于Mayo官方LDCT数据训练的ema_model在测试数据上的PSNR为41.61，SSIM为0.9548，RMSE为16.92。这可能是由于基于MIRT仿真的LDCT数据与Mayo官方数据之间存在噪声分布差异。论文中所有关于Mayo 2016数据集的实验均基于仿真数据完成，对比模型的训练也同样基于仿真数据。通过简单实验发现，基于Mayo官方数据训练的对比模型性能指标也有下降，我们的方法仍然表现最佳。
- 在Mayo官方数据上实验时，我发现增大batch size对模型性能提升明显。如果您在复现代码时仍然遇到问题，欢迎随时讨论。

- The "ema_model" is used for inference, and there is no need to load the "model" and "optimizer". I have updated models/basic_template.py and utils/loggerx.py, and uploaded test_mayo2016.sh for inference.
- The "ema_model", trained on the official Mayo LDCT dataset, achieved a PSNR of 41.61, SSIM of 0.9548, and RMSE of 16.92 on the test data. This may be due to differences in noise distribution between the MIRT-simulated LDCT data and the official Mayo data. All experiments involving the Mayo 2016 dataset in the paper were conducted using simulated data, and the comparison models were also trained on simulated data. Simple experiments show that the performance metrics of comparison models trained on the official Mayo dataset also declined, while our method still achieved the best performance.
- During experiments on the official Mayo dataset, I found that increasing the batch size improved model performance.

**Comment by qgao21** [comment]
您好，
- ema_model是用于推理的模型，model和optimizer不需要加载。我已更新了models/basic_template.py和utils/loggerx.py，并上传了test_mayo2016.sh供推理使用。
- 基于Mayo官方LDCT数据训练的ema_model在测试数据上的PSNR为41.61，SSIM为0.9548，RMSE为16.92。这可能是由于基于MIRT仿真的LDCT数据与Mayo官方数据之间存在噪声分布差异。论文中所有关于Mayo 2016数据集的实验均基于仿真数据完成，对比模型的训练也同样基于仿真数据。通过简单实验发现，基于Mayo官方数据训练的对比模型性能指标也有下降，我们的方法仍然表现最佳。
- 在Mayo官方数据上实验时，我发现增大batch size对模型性能提升明显。如果您在复现代码时仍然遇到问题，欢迎随时讨论。


- The "ema_model" is used for inference, and there is no need to load the "model" and "optimizer". I have updated models/basic_template.py and utils/loggerx.py, and uploaded test_mayo2016.sh for inference.
- The "ema_model", trained on the official Mayo LDCT dataset, achieved a PSNR of 41.61, SSIM of 0.9548, and RMSE of 16.92 on the test data. This may be due to differences in noise distribution between the MIRT-simulated LDCT data and the official Mayo data. All experiments involving the Mayo 2016 dataset in the paper were conducted using simulated data, and the comparison models were also trained on simulated data. Simple experiments show that the performance metrics of comparison models trained on the official Mayo dataset also declined, while our method still achieved the best performance.
- During experiments on the official Mayo dataset, I found that increasing the batch size improved model performance.

**Comment by qgao21** [comment]
您好，
1. ema_model是用于推理的模型，model和optimizer不需要加载。我已更新了models/basic_template.py和utils/loggerx.py，并上传了test_mayo2016.sh供推理使用。
2. 基于Mayo官方LDCT数据训练的ema_model在测试数据上的PSNR为41.61，SSIM为0.9548，RMSE为16.92。这可能是由于基于MIRT仿真的LDCT数据与Mayo官方数据之间存在噪声分布差异。论文中所有关于Mayo 2016数据集的实验均基于仿真数据完成，对比模型的训练也同样基于仿真数据。通过简单实验发现，基于Mayo官方数据训练的对比模型性能指标也有下降，我们的方法仍然表现最佳。
3. 在Mayo官方数据上实验时，我发现增大batch size对模型性能提升明显。如果您在复现代码时仍然遇到问题，欢迎随时讨论。

- The "ema_model" is used for inference, and there is no need to load the "model" and "optimizer". I have updated models/basic_template.py and utils/loggerx.py, and uploaded test_mayo2016.sh for inference.
- The "ema_model", trained on the official Mayo LDCT dataset, achieved a PSNR of 41.61, SSIM of 0.9548, and RMSE of 16.92 on the test data. This may be due to differences in noise distribution between the MIRT-simulated LDCT data and the official Mayo data. All experiments involving the Mayo 2016 dataset in the paper were conducted using simulated data, and the comparison models were also trained on simulated data. Simple experiments show that the performance metrics of comparison models trained on the official Mayo dataset also declined, while our method still achieved the best performance.
- During experiments on the official Mayo dataset, I found that increasing the batch size improved model performance.

**Comment by kklay11** [comment]
> 您好，
> 
> 1. ema_model是用于推理的模型，model和optimizer不需要加载。我已更新了models/basic_template.py和utils/loggerx.py，并上传了test_mayo2016.sh供推理使用。
> 2. 基于Mayo官方LDCT数据训练的ema_model在测试数据上的PSNR为41.61，SSIM为0.9548，RMSE为16.92。这可能是由于基于MIRT仿真的LDCT数据与Mayo官方数据之间存在噪声分布差异。论文中所有关于Mayo 2016数据集的实验均基于仿真数据完成，对比模型的训练也同样基于仿真数据。通过简单实验发现，基于Mayo官方数据训练的对比模型性能指标也有下降，我们的方法仍然表现最佳。
> 3. 在Mayo官方数据上实验时，我发现增大batch size对模型性能提升明显。如果您在复现代码时仍然遇到问题，欢迎随时讨论。
> 
> * The "ema_model" is used for inference, and there is no need to load the "model" and "optimizer". I have updated models/basic_template.py and utils/loggerx.py, and uploaded test_mayo2016.sh for inference.
> * The "ema_model", trained on the official Mayo LDCT dataset, achieved a PSNR of 41.61, SSIM of 0.9548, and RMSE of 16.92 on the test data. This may be due to differences in noise distribution between the MIRT-simulated LDCT data and the official Mayo data. All experiments involving the Mayo 2016 dataset in the paper were conducted using simulated data, and the comparison models were also trained on simulated data. Simple experiments show that the performance metrics of comparison models trained on the official Mayo dataset also declined, while our method still achieved the best performance.
> * During experiments on the official Mayo dataset, I found that increasing the batch size improved model performance.

明白了，您所有使用的数据包括25%剂量（尽管官方提供了此数据）都是自己模拟得到的，所以和我使用官方数据的结果有出入。
感谢您的回复和对项目的持久维护。

**Comment by chen200103** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/103831184/378653613-86d47b5f-c861-4e62-9652-50edd824dccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjU0NjMsIm5iZiI6MTcyOTU2NTE2MywicGF0aCI6Ii8xMDM4MzExODQvMzc4NjUzNjEzLTg2ZDQ3YjVmLWM4NjEtNGU2Mi05NjUyLTUwZWRkODI0ZGNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMjQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmMyYjJhMTJkNjNiZTliOGViNWYxYjc3NjA5NThmOTU1ZTljZDUxYjZjYTRmZDc0YTU0NGRlNGJhMDI5MDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.en_g58xJBMeJceWytdG4yGxu55JF-sexpJ6uJfH8jzU)作者你好，我看到你只上传了ema_model一个文件。测试报错发现还需要其他两个模型文件
> > 还有一个问题，我复现了两次mayo_2016的结果各指标都比你中的低明显（比如psnr我是41左右，你译文43.92±1.33），代码计算指标啥的都不动，期待你的解答@qgao21
> 
> <img alt="PixPin_2024-10-22_10-40-39" width="723" src="https://private-user-images.githubusercontent.com/103831184/378660808-d7e28b89-29c9-46b5-8d4b-4f88ea6a4bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTgyMzAsIm5iZiI6MTczMDAxNzkzMCwicGF0aCI6Ii8xMDM4MzExODQvMzc4NjYwODA4LWQ3ZTI4Yjg5LTI5YzktNDZiNS04ZDRiLTRmODhlYTZhNGJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwODMyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjcwZTQ5MjU5ZWMxYThkZWM4ZTQyN2E5MjU3OWRlNTM4NWM1MjQyODM2Mzc0YjRmZDQyZGUzOWExMWM1OTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._5gGJ6tY5elrscfq7QGn8mLETxK5nQxYuWRgflvao4g">
> 我修改了代码，用您上传的模型文件测试的结果分数也是这样的

请问您是怎么加载预训练模型的呢？

**Comment by chen200103** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/103831184/378653613-86d47b5f-c861-4e62-9652-50edd824dccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjU0NjMsIm5iZiI6MTcyOTU2NTE2MywicGF0aCI6Ii8xMDM4MzExODQvMzc4NjUzNjEzLTg2ZDQ3YjVmLWM4NjEtNGU2Mi05NjUyLTUwZWRkODI0ZGNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMjQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmMyYjJhMTJkNjNiZTliOGViNWYxYjc3NjA5NThmOTU1ZTljZDUxYjZjYTRmZDc0YTU0NGRlNGJhMDI5MDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.en_g58xJBMeJceWytdG4yGxu55JF-sexpJ6uJfH8jzU)作者你好，我看到你只上传了ema_model一个文件。测试报错发现还需要其他两个模型文件
> > 还有一个问题，我复现了两次mayo_2016的结果各指标都比你中的低明显（比如psnr我是41左右，你译文43.92±1.33），代码计算指标啥的都不动，期待你的解答@qgao21
> 
> <img alt="PixPin_2024-10-22_10-40-39" width="723" src="https://private-user-images.githubusercontent.com/103831184/378660808-d7e28b89-29c9-46b5-8d4b-4f88ea6a4bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjY5MTEsIm5iZiI6MTczMDAyNjYxMSwicGF0aCI6Ii8xMDM4MzExODQvMzc4NjYwODA4LWQ3ZTI4Yjg5LTI5YzktNDZiNS04ZDRiLTRmODhlYTZhNGJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMDU2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjQ0YmU3YzQ4M2ViMjVmNjhiMThhODBmZmFhMDBhMjQwZTE2ZjcwNDRhOTBiMWVjNDQxNmIxOWU3ZjhhYmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bwLPEEp7YQ85rokdNWSxLgMJjiPijuFjPpDScL1Uzow">
> 我修改了代码，用您上传的模型文件测试的结果分数也是这样的

请问您是怎么加载ema_model的呢？我加载进来的ema_model可以运行，但是结果是nan

**Comment by chen200103** [comment]
作者您好，我将ema_model-150000放到/output/corediff_dose25_mayo_2016/save_models目录下，然后下载了mayo中L506的数据集，将前998份数据用于测试，使用您提供的test_mayo2016.sh运行，但是结果确实这样，我是不是哪一步出错或者漏了？
![image](https://github.com/user-attachments/assets/597eb1e5-11b7-4dd6-a561-a920029951b5)
@qgao21

**Comment by kklay11** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/103831184/378653613-86d47b5f-c861-4e62-9652-50edd824dccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjU0NjMsIm5iZiI6MTcyOTU2NTE2MywicGF0aCI6Ii8xMDM4MzExODQvMzc4NjUzNjEzLTg2ZDQ3YjVmLWM4NjEtNGU2Mi05NjUyLTUwZWRkODI0ZGNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMjQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmMyYjJhMTJkNjNiZTliOGViNWYxYjc3NjA5NThmOTU1ZTljZDUxYjZjYTRmZDc0YTU0NGRlNGJhMDI5MDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.en_g58xJBMeJceWytdG4yGxu55JF-sexpJ6uJfH8jzU)作者你好，我看到你只上传了ema_model一个文件。测试报错发现还需要其他两个模型文件
> > > 还有一个问题，我复现了两次mayo_2016的结果各指标都比你中的低明显（比如psnr我是41左右，你译文43.92±1.33），代码计算指标啥的都不动，期待你的解答@qgao21
> > 
> > 
> > <img alt="PixPin_2024-10-22_10-40-39" width="723" src="https://private-user-images.githubusercontent.com/103831184/378660808-d7e28b89-29c9-46b5-8d4b-4f88ea6a4bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjY5MTEsIm5iZiI6MTczMDAyNjYxMSwicGF0aCI6Ii8xMDM4MzExODQvMzc4NjYwODA4LWQ3ZTI4Yjg5LTI5YzktNDZiNS04ZDRiLTRmODhlYTZhNGJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMDU2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjQ0YmU3YzQ4M2ViMjVmNjhiMThhODBmZmFhMDBhMjQwZTE2ZjcwNDRhOTBiMWVjNDQxNmIxOWU3ZjhhYmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bwLPEEp7YQ85rokdNWSxLgMJjiPijuFjPpDScL1Uzow">
> > 我修改了代码，用您上传的模型文件测试的结果分数也是这样的
> 
> 请问您是怎么加载ema_model的呢？我加载进来的ema_model可以运行，但是结果是nan @kklay11

你数据集数量不对吧，测试的L506应该是五百二十多张

**Comment by qgao21** [comment]
@chen200103 确实你的测试集不太对，L506只有524张2D slice（526张去掉首尾）。

**Comment by chen200103** [comment]
> > > > ![图像](https://private-user-images.githubusercontent.com/103831184/378653613-86d47b5f-c861-4e62-9652-50edd824dccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjU0NjMsIm5iZiI6MTcyOTU2NTE2MywicGF0aCI6Ii8xMDM4MzExODQvMzc4NjUzNjEzLTg2ZDQ3YjVmLWM4NjEtNGU2Mi05NjUyLTUwZWRkODI0ZGNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMjQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmMyYjJhMTJkNjNiZTliOGViNWYxYjc3NjA5NThmOTU1ZTljZDUxYjZjYTRmZDc0YTU0NGRlNGJhMDI5MDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.en_g58xJBMeJceWytdG4yGxu55JF-sexpJ6uJfH8jzU)作者你好，我看到你只上传了ema_model一个文件。测试报错发现还需要其他两个模型文件
> > > > 还有一个问题，我复现了两次mayo_2016的结果各指标都比你中的低明显（比如psnr我是41左右，你译文43.92±1.33），代码计算指标啥的都不动，期待你的解答@qgao21
> > > 
> > > 
> > > <img alt="PixPin_2024-10-22_10-40-39" width="723" src="https://private-user-images.githubusercontent.com/103831184/378660808-d7e28b89-29c9-46b5-8d4b-4f88ea6a4bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjY5MTEsIm5iZiI6MTczMDAyNjYxMSwicGF0aCI6Ii8xMDM4MzExODQvMzc4NjYwODA4LWQ3ZTI4Yjg5LTI5YzktNDZiNS04ZDRiLTRmODhlYTZhNGJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMDU2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjQ0YmU3YzQ4M2ViMjVmNjhiMThhODBmZmFhMDBhMjQwZTE2ZjcwNDRhOTBiMWVjNDQxNmIxOWU3ZjhhYmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bwLPEEp7YQ85rokdNWSxLgMJjiPijuFjPpDScL1Uzow">
> > > 我修改了代码，用您上传的模型文件测试的结果分数也是这样的
> > 
> > 
> > 请问您是怎么加载ema_model的呢？我加载进来的ema_model可以运行，但是结果是nan @kklay11
> 
> 你数据集数量不对吧，测试的L506应该是五百二十多张，你应该是下的官方数据集Test里面的，大多数用的都是train数据，前9个患者用来训练，最后一个用来测试

是下错了，谢谢

**Comment by Gigarrum** [comment]
Hi @qgao21! 

Thanks for sharing the pre-trained model! 

Sorry for a very delayed answer by my part, I just started to try to use it in some denoising experiments. 

I am currently having some difficulties on how to load the model in my scripts and use it to infer over images but I will open another issue related to that!

Thanks a lot!

**Comment by lomoly** [comment]
我已经训练好该模型，生成数个ema_model文件，现在我需要用训练好的模型对新数据集做一个外部测试，新数据集选自mayo2020中部分数据，我已将数据预处理完，变成numpy格式，之后我该怎么做呢，直接用test.sh吗？？
